services:
  app:
    image: mukezhz/heynats:latest
    container_name: heynats_app
    ports:
      - "5000:5000"
    depends_on:
      - nats
  nats:
    image: nats:2.12.0
    container_name: heynats_server
    volumes:
      - ./nats_data:/tmp/jetstream
    ports:
      - "4222:4222"
      - "8222:8222"